config/routes.rb
Considerating::Application.routes.draw do
  
  resources :users
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :considerations, :only => [:create, :show, :index, :destroy, :all, :update]
  resources :votes, :only => [:create, :destroy]
  
  resources :users do
  	resources :considerations
  	resources :votes
  end
  
  resources :users do
  	member do
  		get :voteds
  	end
  end
  
  resources :considerations do
  	resources :votes
  end
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy', :as => :signout
  
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  
  match '/new', :to => 'pages#new'
  
  match '/index', :to => 'considerations#index'
  match '/search' => 'considerations#search'
  
  root :to => 'pages#home'
  
  

end

app/views/shared/_consideration_form.html.erb
<%= form_for @new_consideration, :class => "span-two-thirds" do |f| %>
		<%= f.text_area :content, :maxlength => 1000, 
    					:class => "new-consideration-field", 
    					:value => "Submit a new consideration here.", 
    					:onFocus => "if (this.value == 'Submit a new consideration here.') 
							{this.value=''};",  
    					:onBlur => "if (this.value == '') 
    						{this.value='Submit a new consideration here.'};" %>
    	<div id="new-consideration-button">
    		<%= f.submit "Submit", :class => "btn", :id => "new-cons-button" %>
    	</div>
<% end %>

app/views/shared/_page_bottom.html.erb
	<% if Consideration.count != 0 %>
			<div id="mini-hero" class="row vote-form">
				<%= render 'users/vote_form' %><br />
			</div>
			<div id="submitted">
				<%= render 'considerations/destroy_consideration' %> 
				submitted by <%= link_to "#{@consideration.user.name}", 
				user_path(@consideration.user) %> on <%= @consideration.created_at.strftime("%-m/%-d/%y") %>
				 • <%= link_to "permalink", consideration_path(@consideration) %>
			</div>
			<div class="tweet">
				<a href="https://twitter.com/intent/tweet?button_hashtag=considerating" class="twitter-hashtag-button" data-text="Considerate or creepy? Vote and help me decide! http://considerating.com/considerations/<%= @consideration.id %>">Tweet</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>
			<div class="mini-hero home-bottom">
				<%= link_to "Random", root_path %> • <%= link_to "View All", index_path %>
			</div>
	<% end %>
</div>

app/views/shared/_results.html.erb
<div id="vote-results">
	<% if @consideration.votes_count != 0 %>
		<canvas id="graph<%= @consideration.id %>" width="440" height="120">fallback</canvas><br />
		<div id="graph-creepy">creepy</div> 
		<div id="graph-considerate">considerate</div>
		<div id="total-vote-count"><%= pluralize(@consideration.votes_count, "vote") %> so far</div>
	<% end %>
</div>
<script type="text/javascript">
	function draw(points) {
		var canvas = document.getElementById('graph<%= @consideration.id %>');  
		var highest = Math.max.apply(Math, points);
		if (canvas.getContext){  
  			var ctx = canvas.getContext('2d');  
  			// drawing code here  		
  			ctx.strokeStyle = "#000000"; 
  			ctx.lineJoin = "round";
  			ctx.lineWidth = 2;
  			ctx.beginPath();
  			ctx.moveTo(0,115);
  			ctx.bezierCurveTo(20, 115, 
  							  20, 115-(points[0]/highest)*100, 
  							  40, 115-(points[0]/highest)*100);
  			for (i=1; i<10; i++) {
  				ctx.bezierCurveTo(20+(i*40), 115-(points[i-1]/highest)*100, 
  							  	  20+(i*40), 115-(points[i]/highest)*100, 
  							  	  40+(i*40), 115-(points[i]/highest)*100);
			}
  			ctx.bezierCurveTo(420, 115-(points[9]/highest)*100, 
  							  420, 115, 
  							  440, 115);
			ctx.shadowColor="black";
			ctx.shadowBlur=1;
  			ctx.stroke();
		} 
	}
	var points<%= @consideration.id %> = [<%= @consideration.v1 %>, <%= @consideration.v2 %>, 
			 	  <%= @consideration.v3 %>, <%= @consideration.v4 %>,
			 	  <%= @consideration.v5 %>, <%= @consideration.v6 %>,
			 	  <%= @consideration.v7 %>, <%= @consideration.v8 %>,
			 	  <%= @consideration.v9 %>, <%= @consideration.v10 %>];
	draw(points<%= @consideration.id %>);
</script>

app/views/shared/_search_form.html.erb
<div class="searchdiv">
	<%= form_tag search_path, :method => :get, :class => "searchform form-inline" do %>
	<span class="searchspan">
	<%= text_field_tag :query, params[:search], 
							:class => "searchfield span2 input-append",
							:value => "Search", 
    						:onFocus => "this.value=''", 
    						:onBlur => "if (this.value == '') 
    						{this.value='Search'};" %><%= submit_tag "  ", 
    																:name => nil, 
    																:class => "searchbutton add-on" %></span>
	<% end %>
</div>

app/views/shared/_vote_logged_out.html.erb
<div id="new-vote-<%= @consideration.id %>">
	<%= form_for @consideration, :remote => true do |f| %>
		<div class="rating_logged_out">
			<%= range_field_tag :rating, :step => "0.1", :in => 10...101 %>
			<div class="vote-creepy">creepy</div> 
			<div class="vote-considerate">considerate</div>
		</div>
		<div class="actions vote-button"><%= f.submit "Vote!", :class => "btn2 span2", :id => "vote-button" %></div>
	<% end %>
</div>