config/routes.rb
Considerating::Application.routes.draw do
  
  resources :users
  resources :sessions,   :only => [:new, :create, :destroy]
  resources :considerations, :only => [:create, :show, :index, :destroy, :all, :update]
  resources :votes, :only => [:create, :destroy]
  
  resources :users do
  	resources :considerations
  	resources :votes
  end
  
  resources :users do
  	member do
  		get :voteds
  	end
  end
  
  resources :considerations do
  	resources :votes
  end
  
  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/signout', :to => 'sessions#destroy', :as => :signout
  
  match '/home', :to => 'pages#home'
  match '/about', :to => 'pages#about'
  
  match '/new', :to => 'pages#new'
  
  match '/index', :to => 'considerations#index'
  match '/search' => 'considerations#search'
  
  root :to => 'pages#home'
  
  

end

app/views/layouts/_footer.html.erb
<div class="bottombar">	
	<span id="footer">
		Concept/administration by <a href="http://thingswemake.com">Josh Sucher</a>, development/design by <a href="http://daniellesucher.com">Danielle Sucher</a>, released under the <a href="http://www.gnu.org/licenses/gpl.html">GNU General Public License.</a>
	</span>
</div>

app/views/layouts/_nav.html.erb
	<div id="user_nav">
		<span class="user_nav">
			<% if current_user %>
				<%= link_to "#{current_user.name}", user_path(current_user) %> |
				<%= link_to "Submit new consideration", '/new' %> |
				<%= link_to "Sign out of Google", signout_path %> |
			<% else %>
				<%= link_to "Sign in with Google to submit new considerations", "/auth/google_oauth2" %> |
			<% end %>
			<%= link_to "View All", '/index' %> |  
			<%= link_to "About", about_path %>
		</span>
	</div>
	<div class="searchdiv">
		<%= render 'shared/search_form' %>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= yield(:title) %>Considerating</title>
  		<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
  		<script type="text/javascript" src="http://use.typekit.com/vff5mnj.js"></script>
		<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
		<script type="text/javascript">
			 var _gaq = _gaq || [];
			 _gaq.push(['_setAccount', 'UA-29376564-1']);
			
			
			 _gaq.push(['_trackPageview']);
			
			 (function() {
			   var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			   ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			   var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			 })();
		</script>
	</head>
	<body>
		<div class="container">
			<%= render 'layouts/nav' %>
			<div id="banner">
				<%= link_to "Considerating.", root_path %>
			</div>
			<div class="main-body">
				<%= yield %>
			</div>
		</div>
	</body>
</html>